Update components
SinisterRectus/Discordia pull request #298
Opened 2021-06-27 15:55 UTC by borsuczyna

Hey, I simply updated Message:update code to update components, I think you should add this: 
```lua
function Message:update(data)
	return self:_modify({
		content = data.content or null,
		embed = data.embed or null,
		components = data.components or null,
	})
end

greetings!

2021-06-27 17:38 UTC, truemedian requested changes
This PR entirely clobbers the README, it shouldn't change it at all. The commit history also a mess that really needs to be rebased into a single commit.

2021-06-27 17:38 UTC, truemedian commented on libs/client/EventHandler.lua
> +end
The indentation here is inconsistent with the rest of discordia, it should be indented with a single tab.

2021-06-27 17:38 UTC, truemedian commented on libs/client/EventHandler.lua
> +	http.request("POST", url, headers, payload)
Making a HTTP request behind the scenes the exact kind of scenario that discordia goes out of it's way to avoid. This shouldn't be here.

2022-01-29 13:22 UTC, callmehSpear commented
Man literally changed the readme file-

2024-10-07 18:43 UTC, closed without merging